### ISSUE TITLE
How to change the console output log level?

### ISSUE THREAD

**Issue by wangtieqiao** [Kotlin/kotlin-jupyter#101]
I noted Jupyter console window flooded with messages like 
<pre>
[main] DEBUG ikotlin - [iopub] snd>: msg[�B�] header = {"date":"2020-09-05T10:38-0400","session":"9ab904195e6e458a80540f630fb943d1","msg_type":"status","msg_id":"c893db00-c22e-4512-b72a-368aa63e46da","version":"5.3","username":"tieqiao"} parentHeader = {"msg_id":"9ab904195e6e458a80540f630fb943d1_0","msg_type":"kernel_info_request","username":"tieqiao","session":"9ab904195e6e458a80540f630fb943d1","date":"2020-09-05T14:38:20.983264Z","version":"5.3"} metadata = {} content = {"execution_state":"idle"}
[main] DEBUG ikotlin - [shell] >rcv: msg[9ab904195e6e458 ... 
</pre>

How to change the log level?

I have looked at the run_kernel.py, and checked my jar_args.json that "debuggerConfig" is empty, 
<pre>
{
    "mainJar": "kotlin-jupyter-kernel-0.8.2.61.jar",
    "mainClass": "org.jetbrains.kotlin.jupyter.IkotlinKt",
    "classPath": [
        "jupyter-lib-0.8.2.61.jar",
        "kotlin-script-runtime-1.4.20-dev-2342.jar",
        "kotlin-reflect-1.4.20-dev-2342.jar",
        "kotlin-stdlib-1.4.20-dev-2342.jar",
        "kotlin-stdlib-common-1.4.20-dev-2342.jar",
        "annotations-13.0.jar",
    ],
    "debuggerConfig": ""
}
</pre>

**Comment by ileasile** [comment]
It's not possible now, see issue #54
