### ISSUE TITLE
Run kotlin-jupyter locally

### ISSUE THREAD

**Issue by RamiSassiR** [Kotlin/kotlin-jupyter#104]
Hello,

I like to run the "kotlin-jupyter" project in my localhost without using **conda** or **Pipe** commands, but by compiling and running the project after cloning it from this repository.
Who can i do this please ?

Thank you,

**Comment by ileasile** [comment]
Hello! Please refer to [this section of README](https://github.com/Kotlin/kotlin-jupyter#from-sources). 
If you have some questions related to this instruction, please ask here. If no, close the issue.
