### ISSUE TITLE
Gradle plugin

### ISSUE THREAD

**Issue by breandan** [Kotlin/kotlin-jupyter#105]
Does kotlin-jupyter plan to provide a Gradle plugin? Here is [some code](https://gist.github.com/breandan/565e4c4ec560705fc81b60bccd768782) I've been using in case it helps. Although specific to the project I am working on, I was thinking it might be useful for others to have a Gradle DSL to configure the JSON manifest and tasks to install/publish/run notebooks.

**Comment by altavir** [comment]
@breandan Lately, it is not required anymore to copy descriptor to the user directory, it could be used from anywhere. Here is the relevant part of the documentation: https://github.com/Kotlin/kotlin-jupyter#supported-libraries (it was not working last time I've checked, but it should soon. As for other parts of the descriptor, you can look at https://github.com/Kotlin/kotlin-jupyter/pull/99. I think that in the end it would be possible to create a major part of the descriptor inside the module and the library descriptor will hold only a jar path and the entry point (maybe default imports as well).

**Comment by ileasile** [comment]
Closing this issue as it was implemented
