### ISSUE TITLE
Irrelevant 'Unresolved reference' popup.

### ISSUE THREAD

**Issue by alshan** [Kotlin/kotlin-jupyter#109]
![image](https://user-images.githubusercontent.com/4430922/99002588-a569b100-250a-11eb-904d-c9074eda6b35.png)

kotlin-jupyter-kernel 0.7.3.10

The popup was relevant earlier but since then I've added the missing import, restarted the kernel and re-run the notebook.

**Comment by ileasile** [comment]
The last dev version is 0.8.2.127, are you sure you're using the correct one?

**Comment by alshan** [comment]
Weird, I do have 0.8.2.127 in my env now. Not sure, where 0.7.3.10 came from )

**Comment by ileasile** [comment]
And is this bug still can be reproduced?

**Comment by alshan** [comment]
Yes, it is. I'm on 0.8.2.150 now.

**Comment by ileasile** [comment]
Reproduced and fixed. New dev version will be availible in ~20 minutes

**Comment by ileasile** [comment]
0.8.2.151
