### ISSUE TITLE
protocol issue with 5.x protocol of Jupyter

### ISSUE THREAD

**Issue by apatrida** [Kotlin/kotlin-jupyter#11]
After seeing this does not work with Jupyter labs newest version, because of:

> Ah, the issue is that we are expecting an idle status after every iopub message per the 5.0 spec: "Changed in version 5.0: Busy and idle messages should be sent before/after handling every request, not just execution." The classic notebook is more lenient because it also supports older protocol versions.
> 
> http://jupyter-client.readthedocs.io/en/latest/messaging.html#kernel-status

**Comment by nikitinas** [comment]
Fixed
