### ISSUE TITLE
The %use magic doesn't allow to specify version range.

### ISSUE THREAD

**Issue by alshan** [Kotlin/kotlin-jupyter#110]
For example, this input:

```
%use lets-plot(api=[1.0,))
```

results in a failure:

> Failed to process '%use lets-plot(api=[1.0,))' command. Unnamed argument is allowed only if library has a single property

See [Version Range Specification](https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html).

**Comment by ileasile** [comment]
It seems that this comma is interpreted as arguments separator. Maybe we should enforce user to use quotes in such cases?

**Comment by ileasile** [comment]
Please use the following syntax
```
lets-plot(api="[1.0,)")
```

with the new dev version of kernel. Previous syntax (without quotes) is still available for simple cases.
