### ISSUE TITLE
Completion bug

### ISSUE THREAD

**Issue by devcrocod** [Kotlin/kotlin-jupyter#113]
If there are several methods to choose from with the same initial types of arguments and for the compliant to press `Tab` and not `Enter`, then in addition to the completion of the method, a type will be added.

For reproduction:
1. 
```
fun test(num1: Int) = 1
fun test(num1: Int, num2: Int) = 2
```
2. Start typing `test` press `Tab`.
Result:
```
test(Int
```
Expected:
```
test(
```

**Comment by devcrocod** [comment]
How it looks
![complbug](https://user-images.githubusercontent.com/19648120/100650310-cb89b080-3354-11eb-995f-d99b0e456482.gif)

**Comment by ileasile** [comment]
Please update to 0.8.3.40 from one of dev channels
