### ISSUE TITLE
Add option to bypass ivy cache for dependencies

### ISSUE THREAD

**Issue by altavir** [Kotlin/kotlin-jupyter#121]
The use-case is the development of libraries and plugins. A typical workflow is to modify the code, then deploy to maven local, load it into the notebook, and test after reloading the kernel. The problem is that ivy caches the dependency and in order to reload the new code with the same version, one needs to manually clean it up from the ivy cache.

The solution is either to allow SNAPSHOT-like behavior with a key or to bypass the cache completely for mavenLocal (i think it is the preferable variant).

**Comment by ileasile** [comment]
As a workaround, use `clearIvyCache` function. You may delete the whole cache or only a part related to some group or artifact.
```
clearIvyCache([group, [artifact, [version]]])
```
