### ISSUE TITLE
Add Cell information to API render method

### ISSUE THREAD

**Issue by altavir** [Kotlin/kotlin-jupyter#128]
I think the renderer should be available of its cell if possible, so it should be `inline fun <reified T : Any> render(noinline renderer: Cell.(T) -> Any)` instead of `inline fun <reified T : Any> render(noinline renderer: (T) -> Any)`.

**Comment by ileasile** [comment]
You have an access to the `Notebook` instance, and you may simply refer this cell as `notebook?.currentCell`, why doesn't it suit you?

**Comment by altavir** [comment]
Did not think about that. I think it would suffice. Still, from API wholeness point of view, it still makes sense. For example, it would be possible to create stand-alone renderers. Of course with `currentCell` it is just cosmetics.
