### ISSUE TITLE
Support multiplatform projects in jupyter.api plugin

### ISSUE THREAD

**Issue by altavir** [Kotlin/kotlin-jupyter#148]
I expect that a typical case for plugin development will be a mpp project with resources generated by JS part and actual integration descriptor in JVM part. 

Currently, this does not work out of the box:
```
An exception occurred applying plugin request [id: 'org.jetbrains.kotlin.jupyter.api', version: '0.8.3.236']
> Failed to apply plugin 'org.jetbrains.kotlin.jupyter.api'.
   > Configuration with name 'compileOnly' not found.
```

**Comment by ileasile** [comment]
Can you share a small MPP project for testing if you have one?

**Comment by altavir** [comment]
I did better :). No tests though and finding proper resource directories could be glitched for non-standard project structure.

**Comment by ileasile** [comment]
The test was added and the problem with the resources should be solved - there is a separate task and output directory for plugin resources, and *processResources tasks depend on it.

**Comment by ileasile** [comment]
See d22030346367664853e5cd05c951fb2468a7a262
