### ISSUE TITLE
Kernel keeps crashing in Win10's Linux subsystem

### ISSUE THREAD

**Issue by circlespainter** [Kotlin/kotlin-jupyter#16]
I know it's untested but... What info can I collect to help troubleshooting?

**Comment by holgerbrandl** [comment]
What's the error message?

**Comment by circlespainter** [comment]
Sorry for the delay, the kernel starts and seems to connect but crashes and keeps crashing when retrying

**Comment by ileasile** [comment]
@circlespainter try reinstalling the kernel from the latest master. If the problem remains, please attach logs from the console where you're running Jupyter notebook/lab server.

**Comment by ileasile** [comment]
I checked it on Linux subsystem (Ubuntu) by myself, and it works like a charm. Don't forget to install java, python and pip:
```
sudo apt update
sudo apt install python3 python3-pip openjdk-8-jre-headless
sudo apt upgrade
python -m pip install jupyter kotlin-jupyter-kernel
```

Then you may run notebook:
```
jupyter notebook --no-browser
```

And then use the link suggested by Jupyter in your browser.
