### ISSUE TITLE
Add support for Kotlin @Deprecated annotation

### ISSUE THREAD

**Issue by alshan** [Kotlin/kotlin-jupyter#185]
I deprecated symbol "lets_plot" in favor of "letsPlot":
```
@Deprecated("", ReplaceWith("letsPlot(data, mapping)"))
fun lets_plot(data: Map<*, *>? = null, mapping: GenericAesMapping.() -> Unit = {}) = letsPlot(data, mapping)
```

In IDEA user can see the deprecated symbol and can choose to auto-fix:

![image](https://user-images.githubusercontent.com/4430922/113787540-3a16ba80-9709-11eb-96c7-16f95857015c.png)

----
In Jupyter notebook user can not tell a deprecated symbol from the new one (and most likely there is no auto-fix provided):

![image](https://user-images.githubusercontent.com/4430922/113787965-fff9e880-9709-11eb-85b6-1b7812992c0f.png)

**Comment by ileasile** [comment]
There is really no autofix and crossed completion variants, but there should be warnings:
![image](https://user-images.githubusercontent.com/20319593/116946950-29b01c00-ac84-11eb-9515-44eeacc2af15.png)

Do you have them?

**Comment by alshan** [comment]
See them but not always - see screenshot for example.
