### ISSUE TITLE
Installation issue on MacOs Mojave

### ISSUE THREAD

**Issue by raveenb** [Kotlin/kotlin-jupyter#21]
Hi,
After cloning and running the install i get an error, informing about java version, i have java and it works properly, not sure whats going on here

➜  kotlin-jupyter git:(master) ./gradlew install
Downloading https://services.gradle.org/distributions/gradle-2.12-all.zip
...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Unzipping /Users/raveenbeemsingh/.gradle/wrapper/dists/gradle-2.12-all/8ywkdai6puj5z81fume4e7njw/gradle-2.12-all.zip to /Users/raveenbeemsingh/.gradle/wrapper/dists/gradle-2.12-all/8ywkdai6puj5z81fume4e7njw
Set executable permissions for: /Users/raveenbeemsingh/.gradle/wrapper/dists/gradle-2.12-all/8ywkdai6puj5z81fume4e7njw/gradle-2.12/bin/gradle

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '10.0.2'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

----
➜  kotlin-jupyter git:(master) java --version
java 10.0.2 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

**Comment by guppyfaced** [comment]
Hi @raveenb, I had a similar issues which I was able to resolve by changing my bash variable $JAVA_HOME  to Java 8.

Ideally, I'd not like to have to do that, but its worked so far.

**Comment by ileasile** [comment]
I will close this issue. If you will get into troubles again, feel free to open a new one.
