### ISSUE TITLE
How to use a dynamic library?

### ISSUE THREAD

**Issue by apahl** [Kotlin/kotlin-jupyter#214]
Hi,  
thanks a lot for this cool project!!

I would like to explore it for cheminformatics analysis and would therefore like to use the Java bindings of the RDKit toolkit.
The bindings consist of a `jar` artifact and a dynamic library (`.so` for Linux).
In the Idea IDE, I configure the program for the location of the dynamic library with this line in the `build.gradle.kts`:

`jvmArgs = listOf("-Djava.library.path=$rdkitKnime")`

with `rdkitKnime` being the path to the dynamic library.

Then, in the program, I call `System.loadLibrary("GraphMolWrap")` once, to actually load the library.

Is there a corresponding possibility to modify the `java.library.path` in kotlin-jupyter?

`@file:Repository("file:///home/pahl/dev/github/knime-rdkit/org.rdkit.knime.bin.linux.x86_64/os/linux/x86_64")`

followed by 

 `System.loadLibrary("GraphMolWrap")`

in a new cell does not work, it gives a `no GraphMolWrap in java.library.path` error.

Many thanks for your help.

Kind regards,  
Axel

**Comment by ileasile** [comment]
Hello! Thanks for your interest!

Does it work for you?
```
val rdkitKnimePath = "..."
System.setProperty("java.library.path", rdkitKnimePath)
System.loadLibrary("GraphMolWrap")
```

**Comment by ileasile** [comment]
Relates to #72

**Comment by apahl** [comment]
Hi, thanks a lot for coming back so quickly.  
Using `System.SetProperty` did unfortunately not work:

![image](https://user-images.githubusercontent.com/9406836/116731469-05391300-a9ea-11eb-8bd5-98f5a717544d.png)

The workaround mentioned in #72 seems to work, though.  
At least I now get past the `System.loadLibrary` call, but then calling an actual function of the package throws an error again:

![image](https://user-images.githubusercontent.com/9406836/116732857-99f04080-a9eb-11eb-9c33-728ed66b426f.png)

Calling this function does work in the IDE.

**Comment by apahl** [comment]
No, I am just tinkering ATM.

But everything required to get the RDKit running on the JVM is available on Github.

The `jar` and the `.so` are in this repo:  
https://github.com/rdkit/knime-rdkit

The `jar` is here:  
https://github.com/rdkit/knime-rdkit/blob/master/org.rdkit.knime.types/lib/org.RDKit.jar

And the `.so` is here:  
https://github.com/rdkit/knime-rdkit/blob/master/org.rdkit.knime.bin.linux.x86_64/os/linux/x86_64/libGraphMolWrap.so

Thanks for your help.

**Comment by ileasile** [comment]
Thanks, reproduced.
It is a weird issue related to classloaders, but I've built up a JAR for you (unpack it from ZIP first). It works without any additional settings, just specify path to it in the `@file:DependsOn()` and you're all set.
[rdkit-jupyter-1.0.0.jar.zip](https://github.com/Kotlin/kotlin-jupyter/files/6408435/rdkit-jupyter-1.0.0.jar.zip)

You may also build this JAR from [this repo](https://github.com/ileasile/rdkit-jupyter) using `./gradlew shadowJar`

**Comment by ileasile** [comment]
![image](https://user-images.githubusercontent.com/20319593/116762283-9d52ee80-aa22-11eb-9257-f4dd7213cc3b.png)

**Comment by ileasile** [comment]
Problem is following. To be successfully used in some code, native library should be loaded by the classloader that loaded this code or by one of its parents. In our case Lines classloaders (classloaders that load compiled snippets classes) have classloaders which load JARs as parents, and that's why the code in these JARs can't see the loaded native libraries. This issue is inside REPL evaluator, and reproduces in IDE scripting (i.e. main.kts scripts) as well.

**Comment by apahl** [comment]
Wow, very cool.  
I did not understand half of your explanation (only getting started with Kotlin and have no real prior experience with the JVM, but have used a number of other programming languages).

Thanks a TON for your help!!!!

Kind regards,  
Axel

**Comment by ileasile** [comment]
Hope it helped!
