### ISSUE TITLE
Autoremove closing bracket when opening is removed

### ISSUE THREAD

**Issue by nikitinas** [Kotlin/kotlin-jupyter#245]
Type
`fun a( `
Closing bracket will be added. After backspace is pressed, closing bracket is not removed.
Refers to all kinds of brackets: (), <>, {}, []

**Comment by ileasile** [comment]
Code mirror code analysis is too primitive to distinguish "less sign" and "triangular bracket". So, for `<>` it is hard to achieve correct behavior. Regarding the bug itself - it's rather easy to fix it, fix will be delivered soon
