### ISSUE TITLE
Update changelog

### ISSUE THREAD

**Issue by altavir** [Kotlin/kotlin-jupyter#253]
Versions and new features are added quite frequently. It is very hard to track what exists in which version. It would be helpful if CHANGELOG.md would track actual deployed version.

**Comment by ileasile** [comment]
@altavir do you have some practice of automation of changelog updating? I'm looking forward to [Changelog plugin](https://github.com/JetBrains/gradle-changelog-plugin), but it is interesting to listen about your experience

**Comment by ileasile** [comment]
Another interesting solution: https://github.com/joffrey-bion/gradle-github-changelog

**Comment by altavir** [comment]
I am using JB changelog plugin and it seems to be sufficient. A good thing is that it has some external API so it is possible to hook it with more complex deploy logic.
