### ISSUE TITLE
Create a separate repository for descriptors

### ISSUE THREAD

**Issue by altavir** [Kotlin/kotlin-jupyter#254]
Currently, merging versions for libraries creates a lot of "noise" for this repository which makes it hard to track actual issues progress, also I believe that in the future, we will have a lot of libraries and it will be hard to track them without "bucket" mechanism like in SDKMan or scoop.

**Comment by ileasile** [comment]
Descriptors repository: https://github.com/ileasile/kotlin-jupyter-libraries
Hope it will be moved under Kotlin soon
