### ISSUE TITLE
Fix Gradle plugin for Multiplatform project

### ISSUE THREAD

**Issue by ileasile** [Kotlin/kotlin-jupyter#255]
When applying Gradle plugin in MPP, following message appears:
```
Single JVM target not found in a multiplatform project
```
It's because multiplatform targets are not available right after applying Kotlin multiplatform plugin.
This may be fixed by running `addDependenciesIfNeeded()` after all configurations are done and targets are available.

**Comment by altavir** [comment]
A workaround is to load inactive plugin:
```kotlin
plugins {
    kotlin("multiplatform")
    kotlin("jupyter.api") apply(false)
}
```
and activate it after `kotlin` block:

```kotlin

//Applying it after kotlin extension to ensure that JVM target is loaded
//because of https://github.com/Kotlin/kotlin-jupyter/issues/255
plugins.apply(org.jetbrains.kotlinx.jupyter.api.plugin.ApiGradlePlugin::class)
```
