### ISSUE TITLE
Dead kernel and couln't load notebook

### ISSUE THREAD

**Issue by permiakovsa** [Kotlin/kotlin-jupyter#271]
Hello! I'm using Ubuntu where I install the kotlin kernerl for jupyter.
When i start the every notebook - i got Dead kernel and restart. After kotlin works. I print hello-world script, save and re-open.
I got empty notebook with
![Снимок экрана от 2021-06-05 16-03-57](https://user-images.githubusercontent.com/42047797/120892794-a2eeb600-c618-11eb-93ac-b33de232033f.png)
![Снимок экрана от 2021-06-05 16-04-05](https://user-images.githubusercontent.com/42047797/120892836-c0238480-c618-11eb-9913-8e8f4b51938f.png)
![Снимок экрана от 2021-06-05 16-04-34](https://user-images.githubusercontent.com/42047797/120892862-dfbaad00-c618-11eb-8a6f-416830f13791.png)

What am I doing wrong with kotlin kernel?

**Comment by ileasile** [comment]
Hi! What kind of Jupyter client do you use?

**Comment by permiakovsa** [comment]
jupyter notebook 6.0.3 installed by pip

**Comment by permiakovsa** [comment]
update - idea - maybe such a case could be force by ubuntu's snap, because I had preinstall project jupyter in ubuntu

**Comment by ileasile** [comment]
Does it work for you to install kernel from sources and try with `jupyter notebook` one more time? I've improved error message in this place so I could understand better what's going on

**Comment by ileasile** [comment]
I've reproduced this bug with help of @polka125, it seems that it was fixed by fd50133c6585bd59e4d938f776b529c2ed4889a8

**Comment by ileasile** [comment]
@polka125 confirmed that bug was fixed

**Comment by ileasile** [comment]
Fixed in version 0.10.0.84
`pip install -i https://test.pypi.org/simple/ kotlin-jupyter-kernel==0.10.0.84`
