### ISSUE TITLE
Maven local resolver creates an empty directory in m2 for missed dependency

### ISSUE THREAD

**Issue by altavir** [Kotlin/kotlin-jupyter#274]
Kotlin kernel v. 0.10.0.40, Kotlin v. 1.5.30-dev-598

When trying to resolve dependency from maven local with a wrong path, an empty directory is created in local `m2` directory with requested coordinates.

**Comment by ileasile** [comment]
Thanks! You may also file resolver-related issues right in youtrack in KT project (Scripts subsystem) assigning them to me or to Ilya Chernikov

**Comment by ileasile** [comment]
Reproduced.
Maven resolver we use creates folders unconditionally before the download (which may be unsuccessful in case if artifact doesn't exist): https://github.com/apache/maven-resolver/blob/master/maven-resolver-connector-basic/src/main/java/org/eclipse/aether/connector/basic/BasicRepositoryConnector.java#L440
We may try to delete empty folders if resolution was unsuccessful, but I don't know if it really matters

**Comment by ileasile** [comment]
I believe it's not an issue actually, at least not an issue of kernel, so I'll close it
