### ISSUE TITLE
Question about the proper way to add custom classes and files

### ISSUE THREAD

**Issue by permiakovsa** [Kotlin/kotlin-jupyter#280]
Hello, I have some packages which I'd like to use in notebook, how could I load the properly, if the *.kt and *.java files located in the same folder of notebook?

**Comment by altavir** [comment]
You can't load `kt` and `java` files. You need them to be compiled. You need to compile them, pack them in the jar, and then load it according to documentation. I think you can use a kotlin scripting compiler for textual inclusion, but I won't recommend that.

**Comment by permiakovsa** [comment]
Got it, thanks for reply!
