### ISSUE TITLE
Make platform available to LibraryDefinitionProducer

### ISSUE THREAD

**Issue by rnett** [Kotlin/kotlin-jupyter#283]
I'm looking at adding integration for [tensorflow](https://github.com/tensorflow/java/issues/275).  There is a large native dependency, and while I can just depend on the all-platforms bundle, I would like to depend on only the current platform's (or error if it's not supported).  Presumably the way to do this would be via a `LibraryDefinitionProducer`, but as far as I can see there is no way to get the platform.  Will there be issues if I use the current JVM's methods (i.e. `System.getProperty("os.name")` in my `LibraryDefinitionProducer`)?

**Comment by ileasile** [comment]
There should be no issues. You may use system properties in your integration class and add dependencies/imports/whatever based on them

**Comment by rnett** [comment]
Nice.  Two further questions:
1. Is there a way to depend on another library w/ the same version as the current integration?  Or to access the asked for version in my integration?
2. Are there any repositories included by default?  I'm looking at integrations like [serialization's](https://github.com/Kotlin/kotlin-jupyter/blob/master/libraries/serialization.json) that don't declare any.

**Comment by ileasile** [comment]
Sorry for delay, I have been vacationing 🌴 

1. You may use `%use` magic in your library init code. For JSON descriptor:
{ "init": ["%use someOtherLib"] }
For new-way integration:
```
onLoaded {
execute("%use someOtherLib")
}
```
2. Repositories included by default are listed here: https://github.com/Kotlin/kotlin-jupyter/blob/0dc5720df110f51e8c505d67e05d5f9d2d2cd5d9/jupyter-lib/shared-compiler/src/main/kotlin/org/jetbrains/kotlinx/jupyter/config/defaultImports.kt#L8
They are Central and JitPack currently.

**Comment by rnett** [comment]
No worries, this isn't urgent.  I should clarify 1: I'm trying to depend on another module in the same project, so for example if you use `@DependsOn("my.lib:a:0.2.0"` I want to depend on `my.lib:b:0.2.0`.  If I understand the `%use` magics right, they would use the configured version from the kernel (which is generally the latest), which wouldn't work if the user was depending on an old version initially.

**Comment by ileasile** [comment]
What I'd do in your case.
1. In buildscript of module `:a`:
`implementation(":b")`
2. Setup publication in both `:a` and `:b`
3. Publish 0.2.0 version of these packages to some repository (mavenLocal or remote)
4. `@DependsOn("my.lib:a:0.2.0")` in notebook should work as you expect

**Comment by rnett** [comment]
Yeah, unfortunately this is combined with the artifact depending on the OS, so it's more like I need to depend on `my.lib:b:jar:$os:0.2.0`.  I think adding a resource file with the current version is as good as I'm going to be able to get, which works well enough.

**Comment by ileasile** [comment]
Yes, resource file with the version should be the way

**Comment by ileasile** [comment]
I'm closing this issue because solution exists and it's hard to invent something better
