### ISSUE TITLE
Allow setting JDK to use

### ISSUE THREAD

**Issue by rnett** [Kotlin/kotlin-jupyter#284]
I have multiple JDKs installed, and I would like to be able to control which one my notebook runs with.  Ideally this would be a per-notebook setting, but a per-jupyter instance setting would also work.  `JAVA_HOME` does not seem to be used, so even just using that would be a significant upgrade.

If it's as simple as it looks (using JAVA_HOME [here](https://github.com/Kotlin/kotlin-jupyter/blob/3e3ebaa0e47ac885f41552583b12b9110bd40740/distrib/run_kotlin_kernel/run_kernel.py#L42)) I can make a PR.

**Comment by ileasile** [comment]
Yes, you can grab JAVA_HOME in the python code you've mentioned and use it for running a kernel. PRs are welcome

**Comment by rnett** [comment]
Trying to import the gradle project gives me lots of `Could not resolve org.jetbrains.kotlin:kotlin-scripting-dependencies:1.5.30-dev-1502.` errors, is there a repository I should add?
