### ISSUE TITLE
Config editor / network based configuration

### ISSUE THREAD

**Issue by altavir** [Kotlin/kotlin-jupyter#31]
Compile-time configuration repository seems to be rather limited. We probably will want to add configuration locally (Jupyter lab has special configuration pages for extensions) and in future, there should be central repository for packages ready for notebook so people could update them without installing new version. 

Low priority.

**Comment by ileasile** [comment]
@altavir  You still can use `@file:DependsOn()` and `@file:Repository()` in runtime. Why doesn't it suit you?

**Comment by altavir** [comment]
Because configuration allows to define renderers and possibly other things, which is quite important. Also what average notebook user will want is a number of community-chosen and approved modules with centralized description. Power user can attach his own dependencies via `DependsOn`, but more general public will prefer to use something that is tested. I think that Kotlin notebook now has significant advantage over regular Python ones because we can define dependencies and versions inside the notebook and make it stable without bothering with external environment.
