### ISSUE TITLE
Dynamic update of cell output

### ISSUE THREAD

**Issue by dbolotin** [Kotlin/kotlin-jupyter#318]
I want to implement a dynamically updateable cell output. To dynamically show the progress of an ongoing operation.

As I understand `DisplayResult` interface has an `id` field which somehow can be used to re-render the object after it was initially displayed in a cell. It seems that the `updateDisplay` method of the `KotlinKernelHost` should do exactly that. Unfortunately I didn't find a way to get an instance of the host object.

Can you please point us in the right direction. Is it even possible with the current kernel version?

Thank you.

**Comment by ileasile** [comment]
Hi! It was technically possible, but not convenient to achieve from the notebook. I've added a couple of additional methods, now you may do something like this:
![update-display-data](https://user-images.githubusercontent.com/20319593/128578978-2ec6893f-d10f-420a-93b7-394632a41307.gif)

**Comment by ileasile** [comment]
Use version 0.10.0.183

**Comment by dbolotin** [comment]
Thank you! It works!
