### ISSUE TITLE
Every execution request increments `execution_count`,  even if `store_history=False`

### ISSUE THREAD

**Issue by strangepleasures** [Kotlin/kotlin-jupyter#326]
According to Jupyter documentation, `execution_count` should be incremented only when `store_history=True`:
"The kernel should have a single, monotonically increasing counter of all execution requests that are made with store_history=True. This counter is used to populate the In[n] and Out[n] prompts. The value of this counter will be returned as the execution_count field of all execute_reply and execute_input messages.".

However, currently even requests with `store_history=False` increment the counter.

**Comment by ileasile** [comment]
Yes, we don't take `silent` and `store_history` into consideration for now
