### ISSUE TITLE
No syntax highlighting and completion.

### ISSUE THREAD

**Issue by mizraelson** [Kotlin/kotlin-jupyter#327]
Hi, I have some issues with jupyter notebook. When I run it on my local computer everything works fine. But when a notebook is running on a remote server via ssh and I open it in the same browser on my local mac the syntax is not highlighted and no code completion is available, but the cells execute just fine. 
 Here is the java version on the remote server:

openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)

Do you know what this might be about?

![image](https://user-images.githubusercontent.com/18702359/132130835-36a734da-1765-4937-9437-9f325f44f79a.png)

**Comment by ileasile** [comment]
Hi! The most possible version of what's going on is the version of jupyter package of your Python installation, as well as version of kernel. Could you please check these versions on your local computer and compare them to the remote one?

**Comment by ileasile** [comment]
I'd also like to look at your browser console output and kernel log

**Comment by ileasile** [comment]
I hope it should be fixed by 5c7f0177d80b41dfccaeedde9990066bf67d823e

**Comment by ileasile** [comment]
Should be fixed in `0.10.0.227`. If not, feel free to reopen
