### ISSUE TITLE
KSP does not work with Kotlin 1.6.0-RC

### ISSUE THREAD

**Issue by breandan** [Kotlin/kotlin-jupyter#342]
It seems like the [KSP version](https://github.com/Kotlin/kotlin-jupyter/blob/ea275e10a97d0f9f29c138e30a557bf648092546/gradle/libs.versions.toml#L5) is incompatible with `1.6.0-RC`. I received the following error when updating to `0.10.3-31` of the Gradle plugin:

```
ksp-1.5.30-1.0.0 might not work with kotlin-1.6.0-RC properly. Please pick the same version of ksp and kotlin plugins.

> Task :compileKotlin
e: .../KotlinJupyter.kt: (8, 42): Unresolved reference: annotations
e: .../KotlinJupyter.kt: (11, 2): Unresolved reference: JupyterLibrary

> Task :compileKotlin FAILED

FAILURE: Build failed with an exception.
```

**Comment by ileasile** [comment]
Thanks, Breandan, I described the problems and provided a possible fix for your build:
https://github.com/breandan/kaliningraph/pull/5

**Comment by ileasile** [comment]
I'll close it because I don't know how to fix it on Jupyter plugin side. If there are some other problems, please report them in a separate issue.
