### ISSUE TITLE
Rendering MimeTypedResult object as plot/image

### ISSUE THREAD

**Issue by cnchann** [Kotlin/kotlin-jupyter#343]
![image](https://user-images.githubusercontent.com/24472833/141258105-40e02619-cffa-4676-be51-1611d4e633be.png)

May I ask if there is a way to render the MimeTypedResult as an image/plot? Thank you so much for the help!

**Comment by ileasile** [comment]
Hi! You seem to use the old version of API, `MimeTypedResult` class is located in another package now:
https://github.com/Kotlin/kotlin-jupyter/blob/a4867787fd1d23de042f140d961af5033450591f/jupyter-lib/api/src/main/kotlin/org/jetbrains/kotlinx/jupyter/api/results.kt#L110

Could you please show the full code (full notebook and/or library source code etc.)?
