### ISSUE TITLE
Maven Releases require dev libraries that are unavailable in Maven

### ISSUE THREAD

**Issue by fmagin** [Kotlin/kotlin-jupyter#344]
There are regular releases [to maven](https://search.maven.org/artifact/org.jetbrains.kotlinx/kotlin-jupyter-kernel) but all releases require development libraries that are not available, e.g. the latest release [`0.10.3-33`](https://search.maven.org/artifact/org.jetbrains.kotlinx/kotlin-jupyter-kernel/0.10.3-33/jar) requires various Kotlin libraries with the version `1.6.20-dev-3702` which are not found on maven.

@ileasile I remember mentioning this to you at some point and you published version [0.9.1-8-1](https://search.maven.org/artifact/org.jetbrains.kotlinx/kotlin-jupyter-kernel/0.9.1-8-1/jar) which does not require any `-dev` libraries and can just be added as a dependency to Gradle. I might still be the only person actively using the kernel in this way, if Maven provides some statistics this would be interesting to know.

**Comment by ileasile** [comment]
@fmagin hey! The main reason of this situation is that some fixes in Kotlin that affect scripting and REPL appear quite often, and to deliver them faster, we use dev builds of Kotlin. I don't know any other users outside JB who use full kernel artifact, but obviously this doesn't mean that it's not possible to build the artifact without dev dependencies for you. I'll write here a new version for you few hours later today

**Comment by ileasile** [comment]
@fmagin new version is `0.10.3-35-1`, please try it

**Comment by fmagin** [comment]
@ileasile https://github.com/Kotlin/kotlin-jupyter/commit/6b634a47f1500ca34d35805704fffa6a9b51e9c2 was a fairly important fix for me, so I'd appreciate it a lot if you could do a release to maven that doesn't depend on `-dev` libraries again

**Comment by ileasile** [comment]
@fmagin I've published `0.11.0-89-1` version based on Kotlin 1.6.0

**Comment by fmagin** [comment]
@ileasile thanks, just updated my tool to use it. Works and it's a significant usability improvement :)
