### ISSUE TITLE
Automatically load stdlib extensions with approprieate JDK

### ISSUE THREAD

**Issue by altavir** [Kotlin/kotlin-jupyter#358]
Currently, only baseline stdlib is loaded automatically when notebook starts. Since kernel knows which JDK is used, it would make sense to load JDK7/JDK8/etc extensions automatically.

In particular, If foun out that I do not have access to Path extensions introduced in stdlib-jdk7 in basic notebook. It is doubly surprising as gradle setup does that automatically nowadays.

**Comment by ileasile** [comment]
I don't like the idea of adding automatically something you maybe will not ever use... But I'll add a method that will allow to add these extensions in one line, it will work like this.
<img width="292" alt="image" src="https://user-images.githubusercontent.com/20319593/163397277-9bdb87bb-2e2e-43e3-a001-195acc4fbb43.png">

**Comment by altavir** [comment]
The thing is that Gradle already does that. So it is about consistency.
