### ISSUE TITLE
Backend Internal error: Exception during IR lowering

### ISSUE THREAD

**Issue by nikitinas** [Kotlin/kotlin-jupyter#360]
Two code cells:
```
val a = 1
```

```
fun b() = a
```
Exception:
```
Backend Internal error: Exception during IR lowering
File being compiled: Line_1.jupyter-kts
The root cause java.lang.RuntimeException was thrown at: org.jetbrains.kotlin.backend.jvm.codegen.FunctionCodegen.generate(FunctionCodegen.kt:50)
```

Fails with `kotlin-script-runtime-1.6.20-M1`, `kotlin-script-runtim-1.7.0-dev-1825` etc.

Works with `kotlin-script-runtime-1.6.20-dev-5432`

**Comment by altavir** [comment]
Seems to be a scripting regression. I think it makes sense to report it to youtrack.
