### ISSUE TITLE
Hi! I have next problem:

### ISSUE THREAD

**Issue by KirillKurdyukov** [Kotlin/kotlin-jupyter#362]
`fun accuracy(lambdas: List<Int>, alpha: Double, n: Int): Double {
    var averageAccuracy = 0.0
    val countParts = 10
    for (testPart in 0 until  countParts) {
        val parts = DataFrame(n, MESSAGES_PREFIX).data()
        val train: List<Message> = (parts.subList(0, testPart) + parts.subList(testPart + 1, countParts)).flatten()
        val test = parts[testPart]
        averageAccuracy += NaiveBayesClassifier(train, lambdas, alpha).fit().accuracy(test)
    }
    return averageAccuracy / countParts
}`
`Backend Internal error: Exception during IR lowering
File being compiled: Line_141.jupyter-kts
The root cause java.lang.RuntimeException was thrown at: org.jetbrains.kotlin.backend.jvm.codegen.FunctionCodegen.generate(FunctionCodegen.kt:50)`

**Comment by KirillKurdyukov** [comment]
a constant from one cell is not visible in another

**Comment by ileasile** [comment]
Hi! What version of kerenl do you use? Try to install latest dev version, the problem should be fixed there.
```
pip install -i https://test.pypi.org/simple/ kotlin-jupyter-kernel==0.11.0.73
```

**Comment by KirillKurdyukov** [comment]
Kotlin kernel v. 0.11.0.100500, Kotlin v. 1.7.0-dev-1825

**Comment by ileasile** [comment]
Yes, it's the issue that was fixed in the latest kernel
