### ISSUE TITLE
Add a function to configure dependencies and repositories in gradle-like manner

### ISSUE THREAD

**Issue by altavir** [Kotlin/kotlin-jupyter#367]
File-level annotations seem to be rather artificial for the notebook. I propose to add a configuration function that will contatin all necesary repositories and dependencies notations. So instead of writing 

```kotlin
@file:Repository("https://repo.kotlin.link")
@file:DependsOn("space.kscience:plotlykt-jupyter:0.5.0")
```
we could do 

```kotlin
notebook.configure{
  repositories{
    maven("https://repo.kotlin.link")
  }
  dependencies{
    implementation("space.kscience:plotlykt-jupyter:0.5.0")
  }
}
```
I specifically made the design exatly the same as gradle configuration. People could just copy configuration blocks from library descriptions or even from `mavenCentral`.

The configuration could be simplified with some shortcuts 

```kotlin
notebook.repositories.maven("https://repo.kotlin.link")
notebook.dependencies += "space.kscience:plotlykt-jupyter:0.5.0"
```

Later some additional configuraion options could be added in the same configuration block.

**Comment by ileasile** [comment]
Yes, it's doable
