### ISSUE TITLE
MIME encoded json gives unexpected result

### ISSUE THREAD

**Issue by andrewhamon** [Kotlin/kotlin-jupyter#387]
### Baseline: JSON output in python

In a python notebook, I can do the following:

```
from IPython.display import JSON


JSON({'a': [1, 2, 3, 4,], 'b': {'inner1': 'helloworld', 'inner2': 'foobar'}})
```
<img width="1349" alt="image" src="https://user-images.githubusercontent.com/5134584/201496640-49eeb467-cb3b-4110-b073-c21e85e6ef52.png">

Which gives a nice interactive, collapsable, searhable display.

### Not working as expected: JSON output in kotlin 

I tried achieving the same with Kotlin:

```
val jsonStr = """
{"a": [1, 2, 3, 4], "b": {"inner1": "helloworld", "inner2": "foobar"}}
"""

MIME("application/json" to jsonStr)
```

<img width="1347" alt="image" src="https://user-images.githubusercontent.com/5134584/201496742-fd869c71-6af4-4e86-a4ad-7fd4741b77b1.png">

This is interpreted as JSON value of string, rather than a JSON object (however Jupyter seems to still think it is showing JSON - see the `root` label and the search box).

Is there a way to properly render a json value with `MIME`?

**Comment by blshao84** [comment]
I have been looking for a solution for exactly the same problem ...
