### ISSUE TITLE
Cannot access class 'jupyter.kotlin.MimeTypedResult'

### ISSUE THREAD

**Issue by haksunlinm** [Kotlin/kotlin-jupyter#388]
Hello,

I am running jupyter with the latest kotlin kernel
Kotlin kernel v. 0.11.0.170, Kotlin v. 1.8.0-dev-3517

![jupyter_version](https://user-images.githubusercontent.com/65719379/202850152-cb8d6b11-c97d-44eb-9361-8d8743f6583d.png)

I am using kotlin-jupyter-api version 0.11.0-183-1.

        <dependency>
            <groupId>org.jetbrains.kotlinx</groupId>
            <artifactId>kotlin-jupyter-api</artifactId>
            <version>0.11.0-183-1</version>
        </dependency>

I tried to put a MIME object (a png) to display in a cell by calling the API.
E.g.,
        return new MimeTypedResult(singletonMap("text/html", html), false, null);

The MimeTypedResult returned is of class
org.jetbrains.kotlinx.jupyter.api.MimeTypedResult 
in kotlin-jupyter-api version 0.11.0-183-1.

However, the notebook gives this error:
Line_19.jupyter-kts (4:3 - 7) Cannot access class 'jupyter.kotlin.MimeTypedResult'. Check your module classpath for missing or conflicting dependencies

I cannot understand why it is looking for 'jupyter.kotlin.MimeTypedResult' instead of 'org.jetbrains.kotlinx.jupyter.api.MimeTypedResult'

![mime_error](https://user-images.githubusercontent.com/65719379/202850198-e1777ccc-119d-45d1-ad45-dab94b7f65ec.png)

I searched the source code in here but can't find anything about jupyter.kotlin.MimeTypedResult or jupyter-kts.

Can someone point me to the right direction please?

**Comment by haksunlinm** [comment]
I just checked that this error does not happen using this version of the jupyter kernel.
pip install kotlin-jupyter-kernel==0.11.0.45

I suspect that there is a bug with the latest version 0.11.0-183-1, perhaps?

In any case, I don't understand how 'jupyter.kotlin.MimeTypedResult' and 'org.jetbrains.kotlinx.jupyter.api.MimeTypedResult' are correlated.

Can someone help please?

**Comment by ileasile** [comment]
Can you share the code of your library? Maybe the problem is in one of the libraries you use transitively?

**Comment by haksunlinm** [comment]
Here is the code snippet.

...

import org.jetbrains.kotlinx.jupyter.api.MimeTypedResult;

...

    /**
     * Perform the actual action of plotting. Use the current parameters and
     * return svg as text strings, and perform a plot. If an error occured,
     * an exception is thrown
     *
     * @return image/svg+xml mime type representation of the plot
     * @throws dev.nm.s2.plot.gnuplot.JGnuplotException This exception is thrown
     *                                                  if an error occured. Use the Debug object to dump information about this
     *                                                  error.
     */
    public MimeTypedResult plot() throws JGnuplotException {
        String svgString = exec.plot(param);
        Map<String, String> map = new HashMap<>();
        map.put("image/svg+xml", svgString);
        return new MimeTypedResult(map, false, null);
    }


...



Thank you for helping!

**Comment by ileasile** [comment]
It's strange) Maybe the version you're using in the notebook differs from the sources? Maybe you could share an artifact you're actually using?

**Comment by haksunlinm** [comment]
To follow up this issue, I have installed the latest jupyterlab and kotlin-jupyter-kernel version 0.11.0.385.

The problem no longer there.

I considered this problem now resolved with the latest version.
