### ISSUE TITLE
Java 10 Support

### ISSUE THREAD

**Issue by Vance-Turner** [Kotlin/kotlin-jupyter#39]
Is it possible to compile the kernel with Java 10 or 11?

**Comment by ileasile** [comment]
Hello! We will add a possibility of changing JVM target via gradle parameter in the nearest release.

**Comment by ileasile** [comment]
@Vance-Turner Now, you may change Java target setting this Gradle property to another value:
https://github.com/Kotlin/kotlin-jupyter/blob/5e6d590d9d8c400b30431457c3970470c5ef703a/gradle.properties#L4

For example, this command will 
```
gradlew install -PjvmTarget=11
```

All supported values of this parameter are listed here: https://kotlinlang.org/docs/reference/using-gradle.html#attributes-specific-for-jvm

**Comment by Vance-Turner** [comment]
Thank-you!
