### ISSUE TITLE
Cannot use RELEASE version in @file:DependsOn

### ISSUE THREAD

**Issue by Vance-Turner** [Kotlin/kotlin-jupyter#40]
It seems the `@file:DependsOn` resolution doesn't support the `RELEASE` version. For example:

`@file:DependsOn("org.junit.jupiter:junit-jupiter-api:RELEASE")` fails with the error:

> :: problems summary ::
> :::: WARNINGS
> 		module not found: org.junit.jupiter#junit-jupiter-api;RELEASE
> 
> 	==== jcenter.bintray.com: tried
> 
> 	  https://jcenter.bintray.com/org/junit/jupiter/junit-jupiter-api/RELEASE/junit-jupiter-api-RELEASE.pom
> 
> 	  -- artifact org.junit.jupiter#junit-jupiter-api;RELEASE!junit-jupiter-api.jar:
> 
> 	  https://jcenter.bintray.com/org/junit/jupiter/junit-jupiter-api/RELEASE/junit-jupiter-api-RELEASE.jar
> 
> 	==== repo.maven.apache.org: tried
> 
> 	  https://repo.maven.apache.org/maven2/org/junit/jupiter/junit-jupiter-api/RELEASE/junit-jupiter-api-RELEASE.pom
> 
> 	  -- artifact org.junit.jupiter#junit-jupiter-api;RELEASE!junit-jupiter-api.jar:
> 
> 	  https://repo.maven.apache.org/maven2/org/junit/jupiter/junit-jupiter-api/RELEASE/junit-jupiter-api-RELEASE.jar
> 
> 	==== jitpack.io: tried
> 
> 	  https://jitpack.io/org/junit/jupiter/junit-jupiter-api/RELEASE/junit-jupiter-api-RELEASE.pom
> 
> 	  -- artifact org.junit.jupiter#junit-jupiter-api;RELEASE!junit-jupiter-api.jar:
> 
> 	  https://jitpack.io/org/junit/jupiter/junit-jupiter-api/RELEASE/junit-jupiter-api-RELEASE.jar
> 
> 	==== central: tried
> 
> 	  https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-api/RELEASE/junit-jupiter-api-RELEASE.pom
> 
> 	  -- artifact org.junit.jupiter#junit-jupiter-api;RELEASE!junit-jupiter-api.jar:
> 
> 	  https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-api/RELEASE/junit-jupiter-api-RELEASE.jar
> 

This issue arose when I was trying to use one of my own JARs installed in a local repository.

**Comment by ileasile** [comment]
RELEASE version is not supported since Maven 3.x, and it is not planned to support it in kernel.
