### ISSUE TITLE
Using host.display inside Renderer leads to strange behavior 

### ISSUE THREAD

**Issue by koperagen** [Kotlin/kotlin-jupyter#431]
I have a renderer created using this api:
org/jetbrains/kotlinx/jupyter/api/renderersHandling.kt:224

```
USE {
    addRenderer(createRenderer({ it.value is Int }, { host, value -> host.display("hi from host.display", null)  }))
}
```
Apparently in this API i should return "rendered" value as a lambda result, so my usage of API is wrong. But results are still quite unexpected:
![image](https://github.com/Kotlin/kotlin-jupyter/assets/12936457/31a51728-a3ea-4422-a74d-313bdf8bb302)

**Comment by koperagen** [comment]
Hm, i think i stumbled upon a renderer that actually needs API that allows `host.display` calls (or some other way to render something two times)

```
USE {
    val kType = typeOf<Pair<AnyFrame, AnyFrame>>()
    addRenderer(createRenderer({ it.isOfCompileTimeType(kType) }, { host, property ->
        val value = property.value
        value as Pair<AnyFrame, AnyFrame>
        host.display(value.first, null)
        host.display(value.second, null)
    }))
}
```

**Comment by ileasile** [comment]
@koperagen I fixed this problem, thank you for reporting
