### ISSUE TITLE
dont fail on additional json payload like user_variables

### ISSUE THREAD

**Issue by maxandersen** [Kotlin/kotlin-jupyter#440]
older kernels like the ones used in google colab sends "user_variables" element.

This makes kotlin kernel fail to run.

Here is log from google colab:
```

at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
--
Nov 24, 2023, 12:33:33 AM | WARNING | Current input: {"allow_stdin":false,"code":"","silent":true,"store_history":false,"user_expressions":{},"user_variables":[]}
```

 could we make the json parsing more lenient and ignore what it does not know?

**Comment by maxandersen** [comment]
basically have `Json { ignoreUnknownKeys = true }` whereever it is messages are read.

**Comment by ileasile** [comment]
Hi! Thanks for pointing this out! Maybe just adding a missing field to the scheme is a better solution? Idea was to keep protocol strict. Will it be possible for you to verify the fix in Google Colab if I prepare a new kernel version?

**Comment by ileasile** [comment]
@maxandersen you can take version 0.12.0-93 to test (or 0.12.0.93 if you're using python dev packages)

**Comment by maxandersen** [comment]
it works!

open this [gist](https://gist.github.com/maxandersen/b3ad22cd39ff95e72a8c54f58580c14d
) with [google colab](http://colab.research.google.com/gist/maxandersen/b3ad22cd39ff95e72a8c54f58580c14d/index.ipynb) and it works.

note: %kotlin-statistics does not work in that notebook but seems to be a jitpack/kotlin kernel issue rather than colab afaics.

**Comment by maxandersen** [comment]
note: I've updated the install-kernel script to have the proxy no longer use "ipc" in name, but more that the core kernel will have "-tcp" added in the end. makes the experience on colab consistent with how it works on all the others.

**Comment by maxandersen** [comment]
Thanks for fixing that!
