### ISSUE TITLE
When reading an image, the process doesn't end

### ISSUE THREAD

**Issue by devcrocod** [Kotlin/kotlin-jupyter#45]
Executing the following cell:

```
import javax.imageio.ImageIO
import java.io.File
val ioImage = ImageIO.read(File("some_image.jpg"))
```
launches new process `IkotlinKt` that doesn't end.

**Comment by altavir** [comment]
Could you try to close the file after read? I mean
```kotlin
val ioImage = File("some_image.jpg").use{
  ImageIO.read(it)
}
```
I do not know the library, but it is possible, that image should be manually released as well...

**Comment by devcrocod** [comment]
`File` and `BufferedImage` don't support `Closeable` interface.

But this is really a problem of implementation ImageIO.
