### ISSUE TITLE
missing options in intellij kotlin jupyter notebook plugin to connect to spring starter

### ISSUE THREAD

**Issue by StefanLobbenmeierObjego** [Kotlin/kotlin-jupyter#468]
I saw this talk about kotlin-jupyter and wanted to replicate it locally: https://www.youtube.com/watch?v=rgkMSZDgbA8&t=14m46s

But downloading the plugin from intellij marketplace I do not see the options to configure the port:
![image](https://github.com/user-attachments/assets/da426cfe-1ffb-44d4-a3c3-92b84ed9d6a4)

I tried versions
- 242.22855.74 (in regular intellij 2024.2.3)
- 243.20847.40 (in intellij 2024.3 eap)

So I was wondering if there is some secret flag to this to get the options to connect to a running kernel or if I just need to be a bit more patient

**Comment by cmelchior** [comment]
Hi @StefanLobbenmeierObjego 

It is still behind a developer flag called, which you need to set in the Registry `kotlin.notebook.allow.attached.kernel`. I am not 100% sure if we have released a plugin version where you can set this yet though.

![image](https://github.com/user-attachments/assets/7c83b554-cd39-4ba3-8ee3-ee9f08916697)

**Comment by StefanLobbenmeierObjego** [comment]
Perfect, many thanks 😄 

> I am not 100% sure if we have released a plugin version where you can set this yet though.

looks like the flag and afterwards the UI is there in the latest EAP release of intellij, syntax completion does not fully work but it seems to be working

![image](https://github.com/user-attachments/assets/b1625237-4c1e-4820-8871-c68ed47cde03)


Looking forward to the official release 🔥

**Comment by ileasile** [comment]
Try to restart session. Also, check the kernel version, it should be one of the latest ones
