### ISSUE TITLE
Unable to import krangl

### ISSUE THREAD

**Issue by MonstraG** [Kotlin/kotlin-jupyter#48]
Installed `minicondo3`, installed `jupyter-notebook` using `conda install -c conda-forge jupyterlab`, installed this kernel using `conda install -c jetbrains kotlin-jupyter-kernel`.

Trying to `%use` `lets-plot` and `krangl`:
![image](https://user-images.githubusercontent.com/17963791/76336245-88476780-6317-11ea-89c6-b6c4efe94f4c.png)
This just throws error.

Trying to `%use` `lets-plot`, but import `krangl` with `@file:DependsOn`:
![image](https://user-images.githubusercontent.com/17963791/76336399-c47ac800-6317-11ea-804c-af2753610415.png)
This throws error when actually referencing `krangl`.

I've also tried to install `krangl` using `conda`: 
`conda install krangl`

but it threw:
```
PackagesNotFoundError: The following packages are not available from current channels:

  - krangl

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
```
Searching for `krangl` on anaconda.com didn't turn up any results.

Either it's just broken, or there is some specific strange way to install/import/use `krangl` which I'm not aware of and which isn't described anywhere in `krangl` or `korlin-jupyter` docs.

**Comment by ileasile** [comment]
Hello! Please try to do the following:
1) Update kernel to version **0.7.41.254.dev1**
2) If there is `.jupyter_kotlin` folder in your home folder, remove.
If nothing helps, please get back to us.

**Comment by ileasile** [comment]
This issue seems to be fixed. If you have some problem, feel free to open a new issue.
