### ISSUE TITLE
How do I add a JAR file into the classpath?

### ISSUE THREAD

**Issue by dclong** [Kotlin/kotlin-jupyter#49]
I tried the following but it didn't work.
```
%use /path/to.jar
```

**Comment by loehndorf** [comment]
I succeeded using
```@file:DependsOn("/path/to.jar")```

**Comment by dclong** [comment]
@loehndorf Thank you very much! I will give it a try.

**Comment by dclong** [comment]
@loehndorf It works! Thank you so much!
