### ISSUE TITLE
Unable to use kernel because of error in parserLibraryDescriptors

### ISSUE THREAD

**Issue by rusinikita** [Kotlin/kotlin-jupyter#66]
I am using Jupyter lab and notebook on mac.

Conda env created from file

```
name: kotlin
channels:
  - conda-forge
  - jetbrains
  - defaults
dependencies:
  - python=3.8
  - jupyterlab
  - kotlin-jupyter-kernel
```

jdk installed by jabba

```
jabba current
zulu@1.8.144
```

I am getting error while running kernel in jypyter notebook or jupyter lab.
[logs.txt](https://github.com/Kotlin/kotlin-jupyter/files/4569860/logs.txt)

Changing versions of jupyterlab (2.0, 1.2) does not solve the problem

**Comment by ileasile** [comment]
@rusinikita Hello! It was just fixed. Please update to the latest version of kernel, `0.8.0.25`, and confirm that the problem has gone.

**Comment by ileasile** [comment]
Fixing commits:
https://github.com/Kotlin/kotlin-jupyter/commit/84a063f683d4cf4f91828953a68e52bb03ede6e6
https://github.com/Kotlin/kotlin-jupyter/commit/f4737886e0f1b6bb95aa66d1c620e96e84b302f6
