### ISSUE TITLE
Failed to load maven-central dependency with @DependsOn

### ISSUE THREAD

**Issue by altavir** [Kotlin/kotlin-jupyter#71]
> `@file:DependsOn("org.apache.commons:commons-math3:3.6.1")`

> Failed to resolve org.apache.commons:commons-math3:3.6.1:
> File 'org.apache.commons:commons-math3:3.6.1' not found
> unresolved dependency: org.apache.commons#commons-math3;3.6.1: configuration not found in org.apache.commons#commons-math3;3.6.1: 'master'. It was required from org.apache.commons#commons-math3-caller;working default

Not sure it is a general problem, or just that precise installation. Leaving it here just in case.

**Comment by ileasile** [comment]
What kernel version do you use?

**Comment by altavir** [comment]
Oops, sorry, forget to add it. Version 1.4.0-dev-7568. Just updated it via main channel in conda.

**Comment by ileasile** [comment]
Is it easily reproducible on your machine?

**Comment by altavir** [comment]
It is reproduced stably on my main computer but works fine on my laptop with a similar system. Probably something broken inside the installation. I've used dev branch before, so it is possible that some migration has broken something. I will try to re-install the kernel.

**Comment by altavir** [comment]
Reinstall did not solve the problem.

**Comment by altavir** [comment]
Using previous version: `@file:DependsOn("org.apache.commons:commons-math3:3.6")` works fine. So the problem is probably somehow connected with local repository state.

**Comment by ileasile** [comment]
Could you find `~/.ivy/cache/org.apache.commons/commons-math3` folder and send it to me, zipped? After that, please remove this folder and try to reproduce the problem again

**Comment by altavir** [comment]
[commons-math3.zip](https://github.com/Kotlin/kotlin-jupyter/files/4882665/commons-math3.zip)
Here you are.

Clearing the cache indeed fixed the problem,

**Comment by ileasile** [comment]
I've added some info about fixing this kind of issues if they accidentally hapen.
