### ISSUE TITLE
Detect transitive dependencies for supported libraries

### ISSUE THREAD

**Issue by breandan** [Kotlin/kotlin-jupyter#75]
I wonder if there is a way to import transitive dependencies by default for supported libraries imported with the `%use` keyword in the same way as the `@file:DependsOn(<coordinates>)`/`@file:Repository(<absolute-path>)` syntax does. Why is it necessary to re-declare all the transitive dependencies for supported libraries in the `json` library descriptor [like so](https://github.com/Kotlin/kotlin-jupyter/blob/26eb6cdb64689b872583f02fe2424c717f65baa3/libraries/deeplearning4j.json#L9-L20)?

**Comment by ileasile** [comment]
Actually, `%use` keyword produces `@file:DependsOn()`/`@file:Repository()` calls, so specifying transitive dependencies shouldn't be needed. Do you have an example of library descriptor which doesn't work without specifying these dependencies?

**Comment by breandan** [comment]
Hmm, maybe I did not phrase this very clearly. I am just wondering why it is necessary for supported libraries to re-declare all dependencies from the Maven POM inside of the JSON library descriptor? In all of the supported libraries, they need to declare the dependencies in the JSON like so:

```
"properties": {
    "v": "1.0.0-beta6",
    "slf4j": "1.7.25",
    "freemarker": "2.3.29"
  },
  "link": "https://github.com/eclipse/deeplearning4j",
  "dependencies": [
    "org.freemarker:freemarker:$freemarker",
    "org.nd4j:nd4j-api:$v",
    "org.nd4j:nd4j-native:$v",
    "org.nd4j:nd4j-native-platform:$v",
    "org.deeplearning4j:deeplearning4j-core:$v",
    "org.deeplearning4j:deeplearning4j-common:$v",
    "org.deeplearning4j:deeplearning4j-datasets:$v",
    "org.deeplearning4j:deeplearning4j-nn:$v",
    "org.deeplearning4j:deeplearning4j-nlp:$v",
    "org.deeplearning4j:deeplearning4j-ui:$v",
    "org.slf4j:slf4j-simple:$slf4j",
    "org.slf4j:slf4j-api:$slf4j"
  ],
```

This the same information that has already been declared in the [Maven POM](https://github.com/eclipse/deeplearning4j/blob/785f130e61a6b291ccf3fca42d8806b50a9680a2/pom.xml#L263), no? Unless the library author explicitly requires a different set of dependencies and versions, I would expect kotlin-jupyter to use the Maven dependencies and versions by default.

**Comment by ileasile** [comment]
Yes, I understand. I think, these transitive dependencies may be safely deleted, it just needs to be checked.

**Comment by breandan** [comment]
I can confirm this now works as expected, previously there was some issue detecting dependencies that seems to have been fixed. Some of the officially supported libraries (e.g. [Spark](https://github.com/Kotlin/kotlin-jupyter/blob/master/libraries/spark.json)) submitted before the fix still include the transitive deps. Thanks!
