### ISSUE TITLE
Publish the cell and display layout API as a separate artifact.

### ISSUE THREAD

**Issue by altavir** [Kotlin/kotlin-jupyter#78]
I mean things like `TypedMIMEContainer` etc. It is required to be able to make plugins. I also think that there should be an abstraction for the current JSON module specification. So things like init code could be loaded directly from the jar.

**Comment by ileasile** [comment]
This thing was implemented, see https://github.com/Kotlin/kotlin-jupyter/blob/master/docs/libraries.md for documentation
