### ISSUE TITLE
Add tested operating systems

### ISSUE THREAD

**Issue by hanslovsky** [Kotlin/kotlin-jupyter#98]
The README says that this kernel has been tested on macOS with Jupyter 6.0.1. What are the criteria to add other operating systems to that list? I have used this kernel on Manjaro Linux with
```
$ mamba list | grep jupyter
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            6.1.6                      py_0    conda-forge
jupyter_console           6.1.0                      py_1    conda-forge
jupyter_core              4.6.3            py38h32f6830_1    conda-forge
kotlin-jupyter-kernel     0.8.2.61                   py_0    jetbrains
```
and a little bit on Windows 10 (but I don't know the exact versions). The only thing that I noticed is that on Windows you cannot delete folders (and probably files) in the `~/.ivy2` cache while a kernel is running.

**Comment by ileasile** [comment]
Hello! Actually, yes, kernel was tested on Windows 10, on Ubuntu Linux and on MacOS. I'll update Readme with this info.
We try to make kernel platform-independent, so if you find some platform-specific issues, please report them here. Regarding your problem with ivy cache: Windows forbids to remove JARS which are currently running (those classes have been loaded), so it seems to be natural behaviour. If you're not able to delete any file/folder, even if it is not used in current kernel classpath — then yes, it seems to be a problem.

**Comment by altavir** [comment]
By the way. Manual cache cleaning is a bit annoying when in development mode (I need to stop kernel, publish artifact to mavenLocal, clean ivy cache and then restart the kernel. I do not think it is a problem outside development.

**Comment by hanslovsky** [comment]
> Hello! Actually, yes, kernel was tested on Windows 10, on Ubuntu Linux and on MacOS. I'll update Readme with this info.

Great, I just wanted to contribute my experience on Linux (and Windows) in case it was untested so far. Other than the file deletion issue on Windows (which is expected Windows behavior), I have not encountered any issues yet.

> I do not think it is a problem outside development.

I think so. Is there an ivy option to always update `SNAPSHOT` dependencies that can be set inside the notebook?

**Comment by ileasile** [comment]
I've updated info about operating systems and frontends

**Comment by ileasile** [comment]
Regarding JARs which cannot be removed after adding to the classpath... I think it's better that it works this way, because if you change the JAR on which some of the added snippets depend it may lead to some unexpected things... So it's OK that you need to restart the kernel to reload dependencies.

**Comment by hanslovsky** [comment]
Thanks for updating the README, this is resolved for me.
